### ISSUE TITLE
Unable to navigate from step with a separate stepAssembly and app.config not in the root folder

### ISSUE THREAD

**Issue by itanneo** [SpecFlowOSS/SpecFlow.VisualStudio#192]
### Used Visual Studio

Visual Studio 2019

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

 <specFlow>
    <unitTestProvider name="NUnit" />
    <runtime missingOrPendingStepsOutcome="Error" />
    <stepAssemblies>
      <stepAssembly assembly="XXX.Test.SpecFlow" />
    </stepAssemblies>
  </specFlow>

### Issue Description

When I try to navigate from a step of my feature, the step is not recognized.
It appends when the step definition is in a different library and that the app.config defining the stepAssembly is not in the root folder of the project. However if I run the test, it works fine.

Workaround: if I copy the app.config in the root folder, it works. I suppose that the extension assumes that the app.config is in the root folder of the project and doesn't look at the <AppConfig> property of the csproj.

Our app.config is shared between several projects, that's why it is not in the root folder of the project.

### Steps to Reproduce

_ Have a project XXX.Test.SpecFlow that contains some steps
- Have a project XXX.Test.Integration containing a feature. The app.config file of this project is not located in the root folder of the project
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XXX.Test.Integration</AssemblyName>
    <AppConfig>..\..\app.config</AppConfig>
    <AppConfigForCompiler>..\..\app.config</AppConfigForCompiler>
  </PropertyGroup>
- Compile the project
- Executing the tests of the feature works correctly
- But it's not possible to navigate from the steps of the feature to the C# code.

**Comment by SabotageAndi** [comment]
How do you get the app.config into your project? Do you have it as linked file?

**Comment by itanneo** [comment]
The config file path is defined in the csproj as below:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XXX.Integration.Nunit</AssemblyName>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.2</LangVersion>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    **<AppConfig>..\..\app.config</AppConfig>**`

**Comment by itanneo** [comment]
I saw in the code that the method VsSpecFlowConfigurationReader.GetConfigFileContent only searches in the folder of the project or in the projectitems. In our case, the app.config doesn't appear in the project items.

Maybe the VsSpecFlowConfigurationReader.GetConfigFileContent method could inspect the csproj and check if there's an "AppConfig" property ?

**Comment by SabotageAndi** [comment]
@itanneo probably, any desire for sending a PR to fix it?

**Comment by itanneo** [comment]
Sure, I'll give it a try after holidays. 

Le 23 juillet 2021 17:15:44 GMT+02:00, Andreas Willich ***@***.***> a écrit :
***@***.*** probably, any desire for sending a PR to fix it?

**Comment by itanneo** [comment]
Hello @SabotageAndi ,
As suggested, I proposed a PR:
https://github.com/SpecFlowOSS/SpecFlow.VisualStudio/pull/193
I didn't find a way to access to the <AppConfig> element value by using the Project/VsProject objects so I used XML parsing of the csproj to get it.
