### ISSUE TITLE
Cannot navigate to feature file from Test Explorer

### ISSUE THREAD

**Issue by MonkeyTennis** [SpecFlowOSS/SpecFlow.VisualStudio#212]
### Used Visual Studio

Visual Studio 2019

### Are the latest Visual Studio updates installed?

Yes

### SpecFlow Section in app.config or content of specflow.json

This simply contains references to stepAssemblies and so I would rather not copy it here entirely:

`{
  "stepAssemblies": [
    { "assembly": "<removed>" },
  ]
}`

### Issue Description

We are using the following version of Visual Studio (VS 2022 was not available in the dropdown list above):

Microsoft Visual Studio Enterprise 2022
Version 17.5.1
VisualStudio.17.Release/17.5.1+33424.131
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.5.0-6.23123.11+271ccd71554f7d28d2f90551aafd0bdeb5d327aa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

SonarLint for Visual Studio   6.13.0.62767
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23123.11+271ccd71554f7d28d2f90551aafd0bdeb5d327aa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio Extension for SpecFlow   1.0
Visual Studio extension for working with SpecFlow projects and Gherkin feature files.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

------------------------------------------
------------------------------------------
------------------------------------------
And the following SpecFlow extension (only showing the most recently installed versions):

# v2022.1.91 - 2022-12-20

* Improve step definition discovery for .NET 7

# v2022.1.89 - 2022-12-15

* Support for .NET 7 projects
* Support for Arm64
* Improve step definition discovery

------------------------------------------
------------------------------------------
------------------------------------------
In previous releases a SpecFlow test could be double clicked in Test Explorer and VS would navigate to the corresponding feature file. Now it instead navigates to the auto-generated feature.cs file.

### Steps to Reproduce

Using the configuration above:

1) View SpecFlow tests via Test Explorer
2) Double click a test

Expected result:
VS navigates to the feature file

Actual result:
VS navigates to the feature.cs file

**Comment by TacoVerhagen** [comment]
I can confirm the issue on Visual Studio 2022 17.5.1 and 17.6 preview, on 5 different machines. Downgrading to 17.4.3 solved the issue

**Comment by MonkeyTennis** [comment]
There has been a VS community fix for this: https://developercommunity.visualstudio.com/t/Test-Explorer-SpecFlow-tests:-goes-to-/10291227
